/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fazConsertos.telas;

import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import fazConsertos.DAL.ConnectionModule;
import java.sql.Connection;
import java.sql.ResultSet;

import net.proteanit.sql.DbUtils;

/**
 *
 * @author felipegiori
 */
public class ClientMainFrame extends javax.swing.JFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    serviceOrderTable table = new serviceOrderTable();
    /**
     * Creates new form ClientMainFrame
     */
    public ClientMainFrame() {
        connection = ConnectionModule.connector();
        initComponents();
        table.setVisible(true);
        clientDesktop.add(table);
 //       pesquisar_cliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientDesktop = new javax.swing.JDesktopPane();
        ClientDate = new javax.swing.JLabel();
        ClientName = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCad = new javax.swing.JMenu();
        MenuCadEditClient = new javax.swing.JMenuItem();
        MenuOrder = new javax.swing.JMenu();
        MenuOrderNewOrder = new javax.swing.JMenuItem();
        MenuHelp = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuOptions = new javax.swing.JMenu();
        MenuOptionsLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("fazConserto - Home - Cliente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        clientDesktop.setPreferredSize(new java.awt.Dimension(935, 460));

        ClientDate.setText("Data");

        ClientName.setText("Bem vindo,");

        MenuCad.setText("Cadastro");

        MenuCadEditClient.setText("Editar Cadastro");
        MenuCadEditClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadEditClientActionPerformed(evt);
            }
        });
        MenuCad.add(MenuCadEditClient);

        jMenuBar1.add(MenuCad);

        MenuOrder.setText("Ordens de Serviço");

        MenuOrderNewOrder.setText("Novo Serviço");
        MenuOrderNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOrderNewOrderActionPerformed(evt);
            }
        });
        MenuOrder.add(MenuOrderNewOrder);

        jMenuBar1.add(MenuOrder);

        MenuHelp.setText("Help");

        jMenuItem3.setText("About");
        MenuHelp.add(jMenuItem3);

        jMenuBar1.add(MenuHelp);

        MenuOptions.setText("Options");

        MenuOptionsLogout.setText("Logout");
        MenuOptionsLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOptionsLogoutActionPerformed(evt);
            }
        });
        MenuOptions.add(MenuOptionsLogout);

        jMenuBar1.add(MenuOptions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(clientDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ClientDate)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ClientName)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(ClientName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClientDate)
                .addGap(6, 6, 6))
        );

        setSize(new java.awt.Dimension(960, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
/*   public void ReturnDefaultSettings() {
        Table.setVisible(false);
        myOrders.setVisible(false);
    }
*/    
    private void MenuOptionsLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOptionsLogoutActionPerformed
        int logout = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Logout", JOptionPane.YES_NO_OPTION);
        if(logout == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_MenuOptionsLogoutActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date date = new Date();
        DateFormat shortDate = DateFormat.getDateInstance(DateFormat.SHORT);
        ClientDate.setText(shortDate.format(date));
    }//GEN-LAST:event_formWindowActivated

    private void MenuOrderNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOrderNewOrderActionPerformed
        NewServiceOrder service = new NewServiceOrder();
        service.setVisible(true);
        clientDesktop.add(service);
        service.moveToFront();
    }//GEN-LAST:event_MenuOrderNewOrderActionPerformed
 /*   private void pesquisar_cliente() {
        String sql = "select * from client where idclient like ?";
        try{
            pst = connection.prepareStatement(sql);
            pst.setString(1,Integer.toString(TelaLogin.id) + "%");
            rs = pst.executeQuery();
            
            serviceOrdersTable.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
*/
    private void MenuCadEditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadEditClientActionPerformed
        EditClient editClient = new EditClient();
        editClient.setVisible(true);
        clientDesktop.add(editClient);
        editClient.moveToFront();
    }//GEN-LAST:event_MenuCadEditClientActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClientDate;
    public javax.swing.JLabel ClientName;
    private javax.swing.JMenu MenuCad;
    private javax.swing.JMenuItem MenuCadEditClient;
    private javax.swing.JMenu MenuHelp;
    private javax.swing.JMenu MenuOptions;
    private javax.swing.JMenuItem MenuOptionsLogout;
    private javax.swing.JMenu MenuOrder;
    private javax.swing.JMenuItem MenuOrderNewOrder;
    private javax.swing.JDesktopPane clientDesktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
