/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fazConsertos.telas;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author felipegiori
 */
public class EmployeeMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeMainFrame
     */
    public EmployeeMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopEmployee = new javax.swing.JDesktopPane();
        employeeName = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        MenuBarEmployee = new javax.swing.JMenuBar();
        MenuCad = new javax.swing.JMenu();
        MenuCadEditRegister = new javax.swing.JMenuItem();
        MenuOrder = new javax.swing.JMenu();
        MenuOrderResume = new javax.swing.JMenuItem();
        MenuHelp = new javax.swing.JMenu();
        MenuHelpAbout = new javax.swing.JMenuItem();
        MenuOptions = new javax.swing.JMenu();
        MenuOptionsLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("fazConsertos - Home - Funcionário");
        setPreferredSize(new java.awt.Dimension(960, 540));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        employeeName.setText("Bem vindo, ");

        labelDate.setText("Data");

        MenuCad.setText("Cadastro");

        MenuCadEditRegister.setText("Editar Cadastro");
        MenuCadEditRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadEditRegisterActionPerformed(evt);
            }
        });
        MenuCad.add(MenuCadEditRegister);

        MenuBarEmployee.add(MenuCad);

        MenuOrder.setText("Relatório");

        MenuOrderResume.setText("Relatório de Serviços");
        MenuOrder.add(MenuOrderResume);

        MenuBarEmployee.add(MenuOrder);

        MenuHelp.setText("Help");

        MenuHelpAbout.setText("Sobre");
        MenuHelp.add(MenuHelpAbout);

        MenuBarEmployee.add(MenuHelp);

        MenuOptions.setText("Options");

        MenuOptionsLogout.setText("Sair");
        MenuOptionsLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOptionsLogoutActionPerformed(evt);
            }
        });
        MenuOptions.add(MenuOptionsLogout);

        MenuBarEmployee.add(MenuOptions);

        setJMenuBar(MenuBarEmployee);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DesktopEmployee)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelDate)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(861, Short.MAX_VALUE)
                .addComponent(employeeName)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(employeeName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DesktopEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(960, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date date = new Date();
        DateFormat shortDate = DateFormat.getDateInstance(DateFormat.SHORT);
        labelDate.setText(shortDate.format(date));
    }//GEN-LAST:event_formWindowActivated

    private void MenuOptionsLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOptionsLogoutActionPerformed
        int logout = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Logout", JOptionPane.YES_NO_OPTION);
        if(logout == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_MenuOptionsLogoutActionPerformed

    private void MenuCadEditRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadEditRegisterActionPerformed
        // TODO add your handling code here:                            
        EditEmployee editEmployee = new EditEmployee();
        editEmployee.setVisible(true);
        DesktopEmployee.add(editEmployee);
        editEmployee.moveToFront();
    }//GEN-LAST:event_MenuCadEditRegisterActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopEmployee;
    private javax.swing.JMenuBar MenuBarEmployee;
    private javax.swing.JMenu MenuCad;
    private javax.swing.JMenuItem MenuCadEditRegister;
    private javax.swing.JMenu MenuHelp;
    private javax.swing.JMenuItem MenuHelpAbout;
    private javax.swing.JMenu MenuOptions;
    private javax.swing.JMenuItem MenuOptionsLogout;
    private javax.swing.JMenu MenuOrder;
    private javax.swing.JMenuItem MenuOrderResume;
    public javax.swing.JLabel employeeName;
    private javax.swing.JLabel labelDate;
    // End of variables declaration//GEN-END:variables
}
