/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fazConsertos.telas;

import fazConsertos.DAL.ConnectionModule;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JInternalFrame;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;


import net.proteanit.sql.DbUtils;

/**
 *
 * @author andrecorreia
 */
public class serviceOrderTable extends javax.swing.JInternalFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null; 
    int rs_OS = 0;
    JDesktopPane serviceDesktop = new javax.swing.JDesktopPane();
    /**
     * Creates new form serviceOrderTable
     */
    public serviceOrderTable() {
        connection = ConnectionModule.connector();
        initComponents();
        pesquisar_cliente();
    }
    
    private void pesquisar_cliente() {
        String sql = "select * from ServiceOrder where idclient like ?";
        try{
            pst = connection.prepareStatement(sql);
            pst.setString(1,Integer.toString(TelaLogin.id) + "%");
            rs = pst.executeQuery();

            serviceOrderTable.setModel(DbUtils.resultSetToTableModel(rs));
           

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MyOrders = new javax.swing.JLabel();
        serviceOrderPanel = new javax.swing.JScrollPane();
        serviceOrderTable = new javax.swing.JTable();
        atualizar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(935, 460));

        MyOrders.setText("Meus Pedidos :");

        serviceOrderPanel.setPreferredSize(new java.awt.Dimension(935, 460));

        serviceOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id da OS", "Data", "Serviço", "Descrição", "Equipamento", "Tempo Estimado", "Preço", "Status", "Id do Cliente"
            }
        ));
        serviceOrderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serviceOrderTableMouseClicked(evt);
            }
        });
        serviceOrderPanel.setViewportView(serviceOrderTable);

        atualizar.setText("Atualizar");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serviceOrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MyOrders)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MyOrders)
                    .addComponent(atualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serviceOrderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceOrderTableMouseClicked
       
         int row = serviceOrderTable.rowAtPoint(evt.getPoint());
         int col = serviceOrderTable.columnAtPoint(evt.getPoint());      
         System.out.println(serviceOrderTable.getValueAt(row, col)); 
         //JOptionPane.showMessageDialog(null, "Clicou na linha " +row+ " "+col); 
         EditClientServiceOrder edso = new EditClientServiceOrder();
         edso.setVisible(true);
         serviceDesktop.add(edso); 
    }//GEN-LAST:event_serviceOrderTableMouseClicked

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
       String sql = "update ServiceOrder set dataOS=?, service=?, description=?, equip=?, EstimatedTime=?, price=?, status=?, idclient=?"
                + "where idOS=?";
       int error = 0;
       try {
            pst = connection.prepareStatement(sql);
            for (int i = 0; i < 3 ; i++){
                 for (int j = 1; j < 9; j++){
                     pst.setString(j, String.valueOf(serviceOrderTable.getValueAt(i, j)));
                     System.out.println(serviceOrderTable.getValueAt(i, j));
                 }
                 pst.setString(9, String.valueOf(serviceOrderTable.getValueAt(i, 0)));
                 System.out.println(pst);
                 rs_OS = pst.executeUpdate();
            }
       }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }finally{
           if(error == 0){
                JOptionPane.showMessageDialog(null, "Dados Atualizados com sucesso!");
            }
        }
    }//GEN-LAST:event_atualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MyOrders;
    private javax.swing.JButton atualizar;
    private javax.swing.JScrollPane serviceOrderPanel;
    private javax.swing.JTable serviceOrderTable;
    // End of variables declaration//GEN-END:variables
}
